[package]
name = "ReihenTests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
cadical = "0.1"
dialoguer = "0.11"
